name: WorldStats
description: WorldStats lets you view stats of worlds easily!
author: Legoboy0215
main: Legoboy\WorldStats\WorldStats
version: 1.0.0
api: [1.12.0]
permissions:
 worldstats:
  default: op
  description: Master permission
  children:
    worldstats.sign:
     default: op
     children:
       worldstats.sign.place:
         default: op
       worldstats.sign.break:
         default: op
    worldstats.cmd:
      default: op
