name: WorldStats
description: WorldStats lets you view stats of worlds easily!
author: Legoboy0215
main: Legoboy\WorldStats\WorldStats
version: 1.3.2
api: [0.13.1+]
commands:
 ws:
  usage: "/ws <update/info>"
  description: "WorldStats Main command"
permissions:
 worldstats:
  default: op
  description: Master permission
  children:
    worldstats.sign:
     default: op
     children:
       worldstats.sign.place:
         default: op
       worldstats.sign.break:
         default: op
    worldstats.cmd:
      default: op
