name: Lookout
main: Legoboy\Lookout\Loader
version: "1.0.0"
api: [1.12.0]
author: Legoboy0215
description: A random little minigame...

commands:
 lookout:
  aliases: [lo]
  description: Lookout command...
  usage: /lookout <end|help|time|setpos|setspawns>

permissions:
 lookout:
  default: op
  description: Master Lookout Permission
  children:
   lookout.cmd:
    default: op
    description: Lookout command permission.
    children:
     lookout.cmd.end:
     default: op
     lookout.cmd.help:
     default: op
     lookout.cmd.time:
     default: true
     lookout.cmd.setpos:
     default: op
     description: Set the position for the item
     lookout.cmd.setspawns:
     default: op
     description: Set the spawns for players.